In [1]:
import numpy as np

print(np.__version__)

1.21.5


In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [20]:
arr = np.array([[[1,2,3,4,5],[11,12,13,14,15]],[[6,7,8,9,10],[16,17,18,19,20]]])

print(arr[0,0,0:2])

print(type(arr))

[1 2]
<class 'numpy.ndarray'>


In [23]:
# array
xArr = np.array([1,2,3,4,5])
xArr

array([1, 2, 3, 4, 5])

In [24]:
# list, tidak bisa dilakukan operasi
a = [1,2,3,4,5]
b = [6,7,8,9,10]

a+b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [28]:
arrA = np.array([1,2,3,4,5])
arrB = np.array([6,7,8,9,10])

arrA+arrB

arrA*arrB

array([ 6, 14, 24, 36, 50])

In [29]:
arrA*10

array([10, 20, 30, 40, 50])

In [30]:
y_pred = np.array([1,0,0,1,1,0,1,1])
labels = np.array([0,1,0,1,1,0,1,1])

mse = (1/len(labels)*np.sum(np.square(y_pred-labels)))
mse

0.25

## Array 0 Dimensi

In [31]:
arr0D = np.array(42) # bentuk skalar
arr0D

array(42)

## Array 1 Dimensi

In [32]:
arr1D = np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


## Array 2 Dimensi

In [33]:
arr2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2D)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Array 3 Dimensi

In [34]:
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Array 0s dan 1s

In [35]:
arr0s = np.zeros(5)
print(arr0s)

[0. 0. 0. 0. 0.]


In [37]:
arr0ss = np.zeros((5,2))
print(arr0ss)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [38]:
arr1s = np.ones(7)
print(arr1s)

[1. 1. 1. 1. 1. 1. 1.]


In [40]:
arr1ss = np.ones((7,7))
print(arr1ss)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [41]:
arr1sss = np.ones((3,4,2))
print(arr1sss)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


## Delete Array

In [49]:
arrDel = np.array([[1,2,3],[4,5,6],[7,8,9]])
# delete index baris 1
arrDel = np.delete(arrDel,1,axis=1)
print(arrDel)

[[1 3]
 [4 6]
 [7 9]]


## Akses Array

In [52]:
# 1D
arr = np.array([1,2,3,4])
print(arr[:-1])

[1 2 3]


In [60]:
# 2D
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,2:-1])

[7]


## Fungsi Arrange

In [63]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [64]:
arr = np.arange(10,30)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


## Shape

In [65]:
print(arr1sss.shape)

(3, 4, 2)


In [70]:
arr = arr.reshape(2,2,-1)
print(arr)

[[[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [77]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr = arr.flatten()
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [79]:
# copy, duplikasi total

arr = np.array([1,2,3,4,5,6,7,8,9,10])
x = arr.copy()
arr[0] = 78
print(arr,x)

[78  2  3  4  5  6  7  8  9 10] [ 1  2  3  4  5  6  7  8  9 10]


In [80]:
# view, duplikasi mengikuti induk

arr = np.array([1,2,3,4,5,6,7,8,9,10])
x = arr.view()
arr[0] = 78
print(arr,x)

[78  2  3  4  5  6  7  8  9 10] [78  2  3  4  5  6  7  8  9 10]


## ndmin

In [82]:
arr = np.array([1,2,3,4,5,6,7,8,9,10], ndmin=3)
arr

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]])

In [83]:
print(arr.shape)

(1, 1, 10)


In [84]:
print(arr.ndim)

3


## iterasi pada array

In [87]:
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])

for x in arr:
    print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12 13 14 15]
 [16 17 18 19 20]]


In [90]:
shp = arr.shape
shp

(2, 2, 5)

## iterasi nditer

In [91]:
## akses skalar

arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [94]:
# menggunakan ndenumerate

arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
for idx, x in np.ndenumerate(arr):
    print(idx,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
(0, 1, 4) 10
(1, 0, 0) 11
(1, 0, 1) 12
(1, 0, 2) 13
(1, 0, 3) 14
(1, 0, 4) 15
(1, 1, 0) 16
(1, 1, 1) 17
(1, 1, 2) 18
(1, 1, 3) 19
(1, 1, 4) 20


## Array Join

In [95]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


In [99]:
# join terhadap 2 array 2D
arr1 = np.array([[1,2,3],[7,8,9]])
arr2 = np.array([[4,5,6],[10,11,12]])
arr = np.concatenate((arr1,arr2),axis=1)

print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [100]:
# menggunakan stack

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.stack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [101]:
# hstack
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [102]:
# vstack

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [105]:
# stack array 2D

arr1 = np.array([[1,2,3],[7,8,9]])
arr2 = np.array([[4,5,6],[10,11,12]])
arr = np.stack((arr1,arr2),axis=1)

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [106]:
# split

arr = np.array([1,2,3,4,5,6])
arr = np.split(arr,3)

print(arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [111]:
arr = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]])
arr = np.split(arr,3,axis=1)

print(arr)

[array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2]]), array([[3, 4],
       [3, 4],
       [3, 4],
       [3, 4]]), array([[5, 6],
       [5, 6],
       [5, 6],
       [5, 6]])]


In [115]:
# where

arr = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
arr = np.where(arr == 4)
arr2 = np.where(arr == 4)

print(arr, arr2)

(array([3]),) (array([], dtype=int64),)


In [113]:
# sort

buah = np.array(['pisang','nangka','nanas','apel','mangga'])
print(np.sort(buah))

['apel' 'mangga' 'nanas' 'nangka' 'pisang']


## Filter

In [116]:
arr = np.array([41,42,43,44])
x = [True,False,True,False]
arr = arr[x]

print(arr)

[41 43]


In [117]:
arr = np.array([41,42,43,44])
x = arr > 42
arr = arr[x]

print(arr)

[43 44]


In [118]:
arr = np.array([[43,42],[75,14]])
x = arr > 42
arr = arr[x]

print(arr)

[43 75]


In [119]:
# lebih dari 1 kondisi

arr = np.array([[48,42],[75,14]])
x = (arr > 42) & (arr % 2 == 0)
arr = arr[x]

print(arr)

[48]


In [120]:
# array 2D

arr = np.array([['1','one'],['2','two'],['3','three'],['4','four'],['5','five']])
arr.shape

(5, 2)

In [122]:
filter_arr = np.array(['two','four'])
arr = arr[np.in1d(arr[:,1], filter_arr)]
arr

array([['2', 'two'],
       ['4', 'four']], dtype='<U5')

## Random

In [123]:
from numpy import random
x = random.randint(100)
print(x)

57


In [124]:
x = random.rand(100)
print(x)

[6.87898490e-04 1.39999617e-02 4.13650934e-01 9.94720612e-01
 4.93649040e-02 7.82694180e-01 2.23535524e-01 7.48692929e-01
 8.72716531e-02 8.10296557e-01 3.60500019e-01 5.61654004e-01
 2.00719867e-02 5.83357283e-01 2.16824562e-01 2.37347427e-01
 4.94454851e-01 4.85896469e-01 6.95880601e-01 4.64297165e-01
 5.59638199e-01 2.62425749e-01 7.96598287e-01 6.83048037e-01
 1.07343634e-01 8.74858670e-01 7.60659550e-01 3.19868343e-01
 8.30052845e-01 2.77635861e-01 6.97432223e-02 2.68645171e-01
 9.20592306e-01 2.73238182e-01 5.29247902e-01 8.64580317e-01
 5.36108158e-01 9.52703853e-01 6.29569198e-01 4.63814569e-01
 9.05773056e-01 3.18290614e-01 8.61677893e-01 8.18635857e-01
 8.14604287e-01 7.66480713e-01 9.26227066e-01 7.73387748e-01
 7.97001515e-01 9.24957889e-01 2.76647421e-01 3.13070560e-01
 3.30990620e-01 6.22921070e-01 9.00453003e-02 9.43646929e-01
 1.21800257e-01 5.11405041e-01 6.51364044e-02 1.03363326e-01
 1.85619002e-01 6.75808267e-01 9.28609982e-01 7.90281773e-01
 1.92840259e-01 7.213078

In [125]:
x = random.randint(100, size=(5))
print(x)

[53 43 65 67 10]


In [126]:
x = random.randint(100, size=(3,5))
print(x)

[[ 8  8 46 74 60]
 [30 40 34 28 95]
 [75 41 21 70 88]]


In [127]:
x = random.choice([3,5,7,9])
print(x)

5


In [128]:
# acak pakai array

arr = np.array([1,2,3,4,5])
random.shuffle(arr)

print(arr)

[2 1 5 3 4]
